name: Bug Report
description: Report a reproducible issue or unexpected behavior in Frakto PostCSS.
title: '[Bug] '
labels: ['bug']
assignees:
  - fraktodev
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. Please fill out the form below as thoroughly as possible.
  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of `@frakto/postcss` are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce the problem.
      placeholder: |
        1. Use this configuration...
        2. Run this command...
        3. See the unexpected output...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, tooling, or anything else relevant.
      placeholder: e.g. macOS 14.5, Node 20.10, pnpm 8.15
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details, links, or screenshots.
