name: Feature Request
description: Propose a new feature or enhancement for Frakto PostCSS.
title: '[Feature] '
labels: ['enhancement']
assignees:
  - fraktodev
body:
  - type: markdown
    attributes:
      value: |
        Have a feature idea? We'd love to hear it. Please explain the motivation and use case clearly.
  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of `@frakto/postcss` are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem are you trying to solve? Why is this feature needed?
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your idea for solving this problem.
      placeholder: I think we could add a new option called `...` that would...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any other approaches or workarounds?
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details, mockups, or related links.
